from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Game(models.Model):	
    user = models.ForeignKey( User, on_delete=models.CASCADE)	
    f1_0 = models.SmallIntegerField(default=0, null=True)	
    f1_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f1_1 = models.SmallIntegerField(default=0, null=True)	
    f1_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f1_score = models.SmallIntegerField(default=0, null=True)	
    f2_0 = models.SmallIntegerField(default=0, null=True)	
    f2_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f2_1 = models.SmallIntegerField(default=0, null=True)	
    f2_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f2_score = models.SmallIntegerField(default=0, null=True)	
    f3_0 = models.SmallIntegerField(default=0, null=True)	
    f3_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f3_1 = models.SmallIntegerField(default=0, null=True)	
    f3_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f3_score = models.SmallIntegerField(default=0, null=True)	
    f4_0 = models.SmallIntegerField(default=0, null=True)	
    f4_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f4_1 = models.SmallIntegerField(default=0, null=True)	
    f4_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f4_score = models.SmallIntegerField(default=0, null=True)	
    f5_0 = models.SmallIntegerField(default=0, null=True)	
    f5_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f5_1 = models.SmallIntegerField(default=0, null=True)	
    f5_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f5_score = models.SmallIntegerField(default=0, null=True)	
    f6_0 = models.SmallIntegerField(default=0, null=True)	
    f6_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f6_1 = models.SmallIntegerField(default=0, null=True)	
    f6_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f6_score = models.SmallIntegerField(default=0, null=True)	
    f7_0 = models.SmallIntegerField(default=0, null=True)	
    f7_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f7_1 = models.SmallIntegerField(default=0, null=True)	
    f7_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f7_score = models.SmallIntegerField(default=0, null=True)	
    f8_0 = models.SmallIntegerField(default=0, null=True)	
    f8_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f8_1 = models.SmallIntegerField(default=0, null=True)	
    f8_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f8_score = models.SmallIntegerField(default=0, null=True)	
    f9_0 = models.SmallIntegerField(default=0, null=True)	
    f9_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f9_1 = models.SmallIntegerField(default=0, null=True)	
    f9_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f9_score = models.SmallIntegerField(default=0, null=True)	
    f10_0 = models.SmallIntegerField(default=0, null=True)	
    f10_0_dt = models.DateTimeField(null=True, blank=True, default=None)
    f10_1 = models.SmallIntegerField(default=0, null=True)	
    f10_1_dt = models.DateTimeField(null=True, blank=True, default=None)
    f10_2 = models.SmallIntegerField(default=0, null=True)	
    f10_2_dt = models.DateTimeField(null=True, blank=True, default=None)
    f10_score = models.SmallIntegerField(default=0, null=True)	
    created = models.DateTimeField(null=True)	
    modified = models.DateTimeField(null=True)	
    delted = models.DateTimeField(null=True)	
    class  Meta:	
        db_table = 'game'
