# Generated by Django 2.0.9 on 2018-10-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('f1_0', models.SmallIntegerField(default=0)),
                ('f1_1', models.SmallIntegerField(default=0)),
                ('f2_0', models.SmallIntegerField(default=0)),
                ('f2_1', models.SmallIntegerField(default=0)),
                ('f3_0', models.SmallIntegerField(default=0)),
                ('f3_1', models.SmallIntegerField(default=0)),
                ('f4_0', models.SmallIntegerField(default=0)),
                ('f4_1', models.SmallIntegerField(default=0)),
                ('f5_0', models.SmallIntegerField(default=0)),
                ('f5_1', models.SmallIntegerField(default=0)),
                ('f6_0', models.SmallIntegerField(default=0)),
                ('f6_1', models.SmallIntegerField(default=0)),
                ('f7_0', models.SmallIntegerField(default=0)),
                ('f7_1', models.SmallIntegerField(default=0)),
                ('f8_0', models.SmallIntegerField(default=0)),
                ('f8_1', models.SmallIntegerField(default=0)),
                ('f9_0', models.SmallIntegerField(default=0)),
                ('f9_1', models.SmallIntegerField(default=0)),
                ('f10_0', models.SmallIntegerField(default=0)),
                ('f10_1', models.SmallIntegerField(default=0)),
                ('f10_2', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
