# Generated by Django 2.1.2 on 2018-11-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='f1_0_dt',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
