# Generated by Django 2.0.9 on 2018-10-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
